<?php

use Illuminate\Database\Seeder;
use Faker\Factory;
use Carbon\Carbon;
class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            //Permission Category
          [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Permission Category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new permission category form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Permission Category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit permission category form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new permission category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update permission category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 2,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionCategoriesController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a permission category',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
//Permission
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new permission form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit permission form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 3,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'PermissionsController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a permission',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            //Roles Service
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'index',
                  'allowed' => '1',
                  'display' => 'Show all Roles',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'create',
                  'allowed' => '1',
                  'display' => 'Open new role form',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'show',
                  'allowed' => '1',
                  'display' => 'Show the single Role',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'allowed' => '1',
                  'display' => 'Open edit role form',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'POST',
                  'action' => 'store',
                  'allowed' => '1',
                  'display' => 'Create a new role',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'allowed' => '1',
                  'display' => 'Update role',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 4,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'RolesController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'allowed' => '1',
                  'display' => 'Delete a role',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],

              //Users Service
              [
                  'permission_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'GET',
                  'action' => 'index',
                  'allowed' => '1',
                  'display' => 'Show all Users',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'GET',
                  'action' => 'create',
                  'allowed' => '1',
                  'display' => 'Open new user form',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'GET',
                  'action' => 'show',
                  'allowed' => '1',
                  'display' => 'Show the single user',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'GET',
                  'action' => 'edit',
                  'allowed' => '1',
                  'display' => 'Open edit user form',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'POST',
                  'action' => 'store',
                  'allowed' => '1',
                  'display' => 'Create a new user',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'PUT',
                  'action' => 'update',
                  'allowed' => '1',
                  'display' => 'Update user',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
              [
                  'permission_category_id' => 5,
                  'namespace' => 'App\Http\Controllers\Admin',
                  'controller' => 'UsersController',
                  'method' => 'DELETE',
                  'action' => 'destroy',
                  'allowed' => '1',
                  'display' => 'Delete an user',
                  'created_at' => Carbon::now()->toDateTimeString(),
                  'updated_at' => Carbon::now()->toDateTimeString(),
              ],
            //Settings Service
            [
                'permission_category_id' => 6,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SettingsController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'View Settings Information',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 6,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'SettingsController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Settings Information',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            //Categories
            [
                'permission_category_id' => 7,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoriesController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Categories',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 7,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoriesController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Categories form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 7,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoriesController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Categories',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 7,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoriesController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Categories form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 7,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoriesController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Categories',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 7,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoriesController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Categories',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 7,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CategoriesController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete an Categories',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            //Teachers
            [
                'permission_category_id' => 8,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'TeachersController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Teachers',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 8,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'TeachersController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Teachers form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 8,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'TeachersController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Teachers',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 8,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'TeachersController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Teachers form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 8,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'TeachersController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Teachers',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 8,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'TeachersController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Teachers',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 8,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'TeachersController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a Teachers',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            //Venues
            [
                'permission_category_id' => 9,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'VenuesController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Venues',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 9,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'VenuesController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Venues form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 9,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'VenuesController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Venues',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 9,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'VenuesController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Venues form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 9,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'VenuesController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Venues',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 9,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'VenuesController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Venues',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 9,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'VenuesController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a Venues',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            //Courses
            [
                'permission_category_id' => 10,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CoursesController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Courses',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 10,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CoursesController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Courses form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 10,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CoursesController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Courses',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 10,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CoursesController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Courses form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 10,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CoursesController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Courses',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 10,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CoursesController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Courses',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 10,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CoursesController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a Courses',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 10,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'CoursesController',
                'method' => 'GET',
                'action' => 'enroll',
                'allowed' => '1',
                'display' => 'Show all guest who interest for this course Courses',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            //Course Enroll
            [
                'permission_category_id' => 11,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationEnrollsController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Course Batch Enroll',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 11,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationEnrollsController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Course Batch Enroll form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 11,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationEnrollsController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Course Batch Enroll',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 11,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationEnrollsController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Course Batch Enroll form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 11,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationEnrollsController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Course Batch Enroll',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 11,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationEnrollsController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Course Batch Enroll',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 11,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationEnrollsController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a Course Batch Enroll',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            //Program Types
            [
                'permission_category_id' => 12,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramTypesController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Program Types',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 12,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramTypesController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Program Types form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 12,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramTypesController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Program Types',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 12,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramTypesController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Program Types form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 12,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramTypesController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Program Types',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 12,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramTypesController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Program Types',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 12,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramTypesController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a Program Types',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            //Programs
            [
                'permission_category_id' => 13,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramsController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Programs',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 13,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramsController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Programs form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 13,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramsController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Programs',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 13,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramsController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Programs form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 13,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramsController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Programs',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 13,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramsController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Programs',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 13,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramsController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a Programs',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 10,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramsController',
                'method' => 'GET',
                'action' => 'enroll',
                'allowed' => '1',
                'display' => 'Show all guest who interest for this Programs',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

            //Program Enrolls
            [
                'permission_category_id' => 14,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramEnrollsController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Program Enrolls',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 14,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramEnrollsController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Program Enrolls form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 14,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramEnrollsController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Program Enrolls',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 14,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramEnrollsController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Program Enrolls form',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 14,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramEnrollsController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Program Enrolls',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 14,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramEnrollsController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Program Enrolls',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 14,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'ProgramEnrollsController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a Program Enrolls',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

//Batches
            [
                'permission_category_id' => 15,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'BatchesController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Batches',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 15,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'BatchesController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Batches',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 15,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'BatchesController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Batches',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 15,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'BatchesController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Batches',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 15,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'BatchesController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Batches',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 15,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'BatchesController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Batches',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 15,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'BatchesController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a Batches',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],

//Allocation
            [
                'permission_category_id' => 16,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationsController',
                'method' => 'GET',
                'action' => 'index',
                'allowed' => '1',
                'display' => 'Show all Course, Batch, Venue, Teacher Allocation',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 16,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationsController',
                'method' => 'GET',
                'action' => 'create',
                'allowed' => '1',
                'display' => 'Open new Course, Batch, Venue, Teacher Allocation',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 16,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationsController',
                'method' => 'GET',
                'action' => 'show',
                'allowed' => '1',
                'display' => 'Show the single Course, Batch, Venue, Teacher Allocation',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 16,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationsController',
                'method' => 'GET',
                'action' => 'edit',
                'allowed' => '1',
                'display' => 'Open edit Course, Batch, Venue, Teacher Allocation',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 16,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationsController',
                'method' => 'POST',
                'action' => 'store',
                'allowed' => '1',
                'display' => 'Create a new Course, Batch, Venue, Teacher Allocation',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 16,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationsController',
                'method' => 'PUT',
                'action' => 'update',
                'allowed' => '1',
                'display' => 'Update Course, Batch, Venue, Teacher Allocation',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'permission_category_id' => 16,
                'namespace' => 'App\Http\Controllers\Admin',
                'controller' => 'AllocationsController',
                'method' => 'DELETE',
                'action' => 'destroy',
                'allowed' => '1',
                'display' => 'Delete a Course, Batch, Venue, Teacher Allocation',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
        ];
        DB::table('permissions')->insert($permissions);


    }
}
